### ISSUE TITLE
1.2.0-beta: Long Boots locked by Long Boots

### ISSUE THREAD

**Issue by nikovaan** [Dinopony/alundra-randomizer#50]
Randomizer version: 1.2.0-beta

    "permalink": "aG40XB/P8QLmWkkkkuqpL6S0lQPRQoQh9JJJJUlVf9iQmGaVQZlwU/oAgogwOQdg9AIGAQQiCQaA=/",
    "hashSentence": "Jess Merman Essence Small",

Long Boots were in Overworld E2 First chest in cave (Sluice Key), which to the best of my knowledge requires Long Boots to enter at all. If you can enter it without Long Boots, then my bad.
Long Boots were also mandatory for the playthrough. Seed was unbeatable as a result.

Full spoiler log attached.

[Jess Merman Essence Small.txt](https://github.com/Dinopony/alundra-randomizer/files/9776196/Jess.Merman.Essence.Small.txt)

**Comment by Dinopony** [comment]
Indeed, this region has a logic simplification that is inaccurate.
The game expects you to be able to reach that node using Sand Cape from the map below, which is of course completely wrong.
This will have to be fixed.

**Comment by Dinopony** [comment]
Fixed in 1b07a0b
