### ISSUE TITLE
Softlock in Sand Cape chest room

### ISSUE THREAD

**Issue by Charncat** [Dinopony/alundra-randomizer#57]
The room where you would normally acquire the Sand Cape can be entered with Flail/Merman Boots but you can only exit with the Sand Cape, which leads to a softlock, if you have bombs you can kill yourself, but if not, you'll have to completely reload.

I'm not really sure how you'd fix it without making the logic really boring (short of always making the chest useless), or allowing you to easily exit the room.

**Comment by Chaoswanderer** [comment]
Or adding a way to save and quit or warp back to jesse's house like in zelda

**Comment by Dinopony** [comment]
This is considered to be "normal" and required knowledge to play the rando, although I agree with you that it doesn't feel good when that happens.
Having some way to warp back to start is definitely being considered, implementing it in a satisfying way is not trivial.
